/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-06-12 06:04:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public final class Admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Admin/../dbconn.jsp", Long.valueOf(1685605591000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("\n");
      out.write("    \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");

	Connection conn = null;
	
	String url = "jdbc:mysql://localhost:3306/regist";
	String id = "root";                  
	String pwd = "campus";
	Class.forName("com.mysql.jdbc.Driver");
	conn = DriverManager.getConnection(url, id, pwd);

      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>회원 관리</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"./Admincss.css\">\n");
      out.write("<style>\n");
      out.write("	@import url('https://fonts.googleapis.com/css2?family=Gugi&family=Jua&display=swap');\n");
      out.write("</style>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("	\n");
      out.write("	$(function(){\n");
      out.write("		$(\"#start\").hide();\n");
      out.write("		$(\"#end\").hide();\n");
      out.write("		\n");
      out.write("		/* 출생년도, 출생월, 출생일을 선택하면 기간을 선택할 수 있도록. ex)출생년도가 1960년~1970년 사이인 사람들을 모두 검색 */\n");
      out.write("		$(\"#search\").change(function(){\n");
      out.write("			if($(\"#search\").val()==\"birth_y\" || $(\"#search\").val()==\"birth_m\" || $(\"#search\").val()==\"birth_d\"){\n");
      out.write("				$(\"#searchtext\").hide();\n");
      out.write("				$(\"#start\").show();\n");
      out.write("				$(\"#end\").show();\n");
      out.write("			}else{\n");
      out.write("				$(\"#searchtext\").show();\n");
      out.write("				$(\"#start\").hide();\n");
      out.write("				$(\"#end\").hide();\n");
      out.write("			}\n");
      out.write("		})\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	function validateSearch(){\n");
      out.write("		var searchtext = document.getElementById('searchtext').value;\n");
      out.write("		var start = document.getElementById('start').value;\n");
      out.write("		var end = document.getElementById('end').value;\n");
      out.write("		\n");
      out.write("		if(!searchtext && (!start || !end)){\n");
      out.write("			alert('검색할 내용을 입력해주세요!!');\n");
      out.write("			return false;\n");
      out.write("		}\n");
      out.write("		else{ return true;}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function validatedelete(){\n");
      out.write("		if(confirm(\"삭제하시겠습니까?\")){\n");
      out.write("			return true;\n");
      out.write("		}\n");
      out.write("		else{\n");
      out.write("			return false;\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"wrapper\">\n");
      out.write("<header>회원&nbsp;관리&nbsp;페이지</header>\n");
      out.write("<aside>\n");
      out.write("&lt;&lt;부서 관리&gt;&gt;\n");
      out.write("	");

		String sql2 = "SELECT * FROM dept";
		PreparedStatement pstmt2 = conn.prepareStatement(sql2);
		ResultSet rs2 = pstmt2.executeQuery();
      out.write("\n");
      out.write("	<form action=Dept_plus.jsp>\n");
      out.write("	<table>\n");
      out.write("		<tr><th>번호</th><th>부서명</th></tr>\n");
      out.write("		");
while(rs2.next()){
      out.write("\n");
      out.write("		<tr><td>");
      out.print(rs2.getInt("dept_no") );
      out.write("</td><td>");
      out.print(rs2.getString("dept_name") );
      out.write("</td>\n");
      out.write("		<td><a href=\"Dept_delete.jsp?dept_no=");
      out.print(rs2.getInt("dept_no") );
      out.write("\" onclick=\"return validatedelete()\">삭제</a></td></tr>\n");
      out.write("		");
}
	
      out.write("\n");
      out.write("	<tr><td><input style=\"width:50px\" type=\"text\" name=\"insert_no\" placeholder=\"번호\"/></td>\n");
      out.write("	<td><input style=\"width:50px\" type=\"text\" name=\"insert_name\" placeholder=\"부서명\"/></td>\n");
      out.write("	<td><input style=\"float:right;width:30px;height:15px;font-size:5pt\" type=\"submit\" value=\"추가\"/></td></tr>\n");
      out.write("	</table></form><br>\n");
      out.write("	<form action=Dept_update.jsp>\n");
      out.write("	<table>\n");
      out.write("		<tr><th>변경</th></tr>\n");
      out.write("		<tr><td><input type=\"text\" style=\"width:50px\" name=\"update_no\" placeholder=\"번호\"/></td></tr>\n");
      out.write("		<tr><td><select name=\"column\" id=\"column\">\n");
      out.write("		<option value=\"dept_no\">번호</option><option value=\"dept_name\">부서명</option></select>\n");
      out.write("		<input style=\"width:50px\" type=\"text\" name=\"content\" placeholder=\"변경사항\"/></td>\n");
      out.write("	</table>\n");
      out.write("	<input style=\"float:right;width:30px;height:15px;font-size:5pt\" type=\"submit\" value=\"변경\"/><br>\n");
      out.write("	</form>\n");
      out.write("	\n");
      out.write("</aside>\n");
      out.write("<section>\n");
      out.write("<form style=\"vertical-align : middle;\" action=\"Search.jsp\" onSubmit=\"return validateSearch();\">\n");
      out.write("<select name=\"search\" id=\"search\" style=\"height:30px\">\n");
      out.write("<script> \n");
      out.write("	var options = ['ID','이름','부서','출생년도','출생월','출생일','전화번호','이메일','우편번호','지번주소','도로명 주소','상세주소','가입일자'];\n");
      out.write("	var value = ['member_id','member_name','dept_name','birth_y','birth_m','birth_d','tel','email','addr_post','addr_lot','addr_road','addr_rest','reg_date']\n");
      out.write("	for(var i=0;i<13;i++){\n");
      out.write("		/* select 항목의 value를 db 테이블의 column으로 설정 */\n");
      out.write("		document.write(\"<option value='\"+value[i]+\"'>\"+options[i]+\"</option>\")\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("</select>\n");
      out.write("<!-- 해당 column에서 검색할 내용 입력 -->\n");
      out.write("<input type=\"text\" style=\"width:300px;height:30px\" name=\"searchtext\" id=\"searchtext\" placeholder=\"검색할 내용을 입력하세요.\"/>\n");
      out.write("<!-- 출생년도, 출생월, 출생일을 선택하면 기간을 선택할 수 있도록. ex)출생년도가 1960년~1970년 사이인 사람들을 모두 검색 -->\n");
      out.write("<input type=\"text\" style=\"width:150px;height:30px\" name=\"start\" id=\"start\" placeholder=\"시작\"/>\n");
      out.write("<input type=\"text\" style=\"width:150px;height:30px\" name=\"end\" id=\"end\" placeholder=\"끝\"/>\n");
      out.write("<input type=\"image\" src=\"https://cdn-icons-png.flaticon.com/128/751/751463.png\" style=\"background-color:#C3FDB8;width:30px;height:30px\"> \n");
      out.write("</form><br>\n");
      out.write("<table> <!-- 처음엔 전체 데이터를 볼 수 있게 --> \n");
      out.write("	<tr style=\"background-color:#B6B6B4\"><th>아이디</th><th>비밀번호</th><th>이름</th><th>성별</th><th>부서</th><th>출생년도</th><th>출생월</th><th>출생일</th><th>양력/음력</th>\n");
      out.write("	<th>폰 번호</th><th>이메일</th><th>수신동의</th><th>우편번호</th><th>지번주소</th><th>도로명주소</th><th>상세주소</th><th>가입일자</th><th>수정/삭제</th></tr>\n");

	String sql = "SELECT * FROM usrregist,dept WHERE usrregist.dept_no=dept.dept_no";
	
	PreparedStatement pstmt = conn.prepareStatement(sql);
	ResultSet rs = pstmt.executeQuery();
	
	while(rs.next()){
		String member_id = rs.getString("member_id");
		String member_pwd = rs.getString("member_pwd");
		String member_name = rs.getString("member_name");
		String member_gender = rs.getString("member_gender");
		String dept_name = rs.getString("dept_name");
		String birth_y = rs.getString("birth_y");
		String birth_m = rs.getString("birth_m");
		String birth_d = rs.getString("birth_d");
		String birth_kind = rs.getString("birth_kind");
		String tel = rs.getString("tel");
		String sms_al = rs.getString("sms_al");
		String email = rs.getString("email");
		String email_al = rs.getString("email_al");
		String addr_post = rs.getString("addr_post");
		String addr_lot = rs.getString("addr_lot");
		String addr_road = rs.getString("addr_road");
		String addr_rest = rs.getString("addr_rest");
		String reg_date = rs.getString("reg_date");
	

      out.write("\n");
      out.write("	<tr style=\"background-color:#F0F8FF\"><td>");
      out.print(member_id );
      out.write("</td><td>");
      out.print(member_pwd );
      out.write("</td><td>");
      out.print(member_name );
      out.write("</td><td>");
      out.print(member_gender );
      out.write("</td><td>");
      out.print(dept_name );
      out.write("</td>\n");
      out.write("	<td>");
      out.print(birth_y );
      out.write("년</td><td>");
      out.print(birth_m );
      out.write("월</td><td>");
      out.print(birth_d );
      out.write("일</td><td>");
      out.print(birth_kind );
      out.write("</td><td>");
      out.print(tel );
      out.write("</td><td>");
      out.print(email );
      out.write("</td><td>");
      out.print(sms_al );
      out.write(',');
      out.print(email_al );
      out.write("</td>\n");
      out.write("	<td>");
      out.print(addr_post );
      out.write("</td><td>");
      out.print(addr_lot );
      out.write("</td><td>");
      out.print(addr_road );
      out.write("</td><td>");
      out.print(addr_rest );
      out.write("</td><td>");
      out.print(reg_date );
      out.write("</td>\n");
      out.write("	<td><a href=\"./Admin_update.jsp?usr_id=");
      out.print(member_id);
      out.write("\">변경</a>/<a href=\"./Admin_delete.jsp?delete_id=");
      out.print(member_id);
      out.write("\">삭제</a></tr>\n");
      out.write("	");
} 
      out.write("\n");
      out.write("	</table> \n");
      out.write("	\n");
      out.write("</section>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
